name: Schedule Test

on:
  schedule:
    - cron: '6,16,26,36,46,56 * * * *'
      timezone: 'Asia/Seoul'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Schedule Test
        run: |
          echo "===================="
          echo "Schedule OK"
          echo "UTC: $(date -u)"
          echo "KST: $(TZ=Asia/Seoul date)"
          echo "===================="
#test
